INSERT INTO CATEGORIAs(NOME) VALUES('Alimentação');
INSERT INTO CATEGORIAs(NOME) VALUES('Saúde');
INSERT INTO CATEGORIAs(NOME) VALUES('Moradia');
INSERT INTO CATEGORIAs(NOME) VALUES('Transporte');
INSERT INTO CATEGORIAs(NOME) VALUES('Educação');
INSERT INTO CATEGORIAs(NOME) VALUES('Lazer');
INSERT INTO CATEGORIAs(NOME) VALUES('Imprevistos');
INSERT INTO CATEGORIAs(NOME) VALUES('Outras');

INSERT INTO RECEITAS(VALOR, DESCRICAO, DATA) VALUES(1920,'SALARIO', '2022-01-22');
INSERT INTO RECEITAS(VALOR, DESCRICAO, DATA) VALUES(1000,'OUTROS', '2022-01-22');
INSERT INTO RECEITAS(VALOR, DESCRICAO, DATA) VALUES(400,'RENDA EXTRA', '2022-01-22');

INSERT INTO DESPESAS(VALOR, DESCRICAO, DATA, CATEGORIA_ID) VALUES(1400, 'Aluguel', '2022-01-23', 3);
INSERT INTO DESPESAS(VALOR, DESCRICAO, DATA, CATEGORIA_ID) VALUES(500, 'Imprevistos', '2022-01-23', 8);


